# Generated by Django 5.2.16 on 2026-07-14 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug (URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True, verbose_name='Slug (URL)')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='Qisqa mazmun')),
                ('body', models.TextField(verbose_name='Matn')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='Muqova rasm')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'E’lon qilingan')], default='draft', max_length=10, verbose_name='Holat')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Bosh sahifada (katta)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Ko‘rishlar')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='E’lon vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_articl_publish_62720b_idx'), models.Index(fields=['status'], name='news_articl_status_a95c4c_idx')],
            },
        ),
    ]
