# Generated by Django 5.2.16 on 2026-07-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='article',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Qisqa mazmun'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_ru',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Qisqa mazmun'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary_uz',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Qisqa mazmun'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
    ]
