# Generated by Django 5.2.16 on 2026-07-20 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_body_en_article_body_ru_article_body_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/%Y/%m/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=250, verbose_name='Izoh')),
                ('caption_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='Izoh')),
                ('caption_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Izoh')),
                ('caption_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.article', verbose_name='Yangilik')),
            ],
            options={
                'verbose_name': 'Yangilik rasmi',
                'verbose_name_plural': 'Yangilik rasmlari (galereya)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
