# Generated by Django 5.2.16 on 2026-07-14 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='USD, EUR, RUB', max_length=3, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('symbol', models.CharField(blank=True, help_text='$, €, ₽', max_length=8, verbose_name='Belgi')),
                ('flag_emoji', models.CharField(blank=True, max_length=8, verbose_name='Bayroq (emoji)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Valyuta',
                'verbose_name_plural': 'Valyutalar',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kurs (so‘m)')),
                ('diff', models.DecimalField(decimal_places=2, default=0, help_text='Bir kun oldingi kursga nisbatan (+ oshgan, − tushgan)', max_digits=10, verbose_name='O‘zgarish')),
                ('date', models.DateField(verbose_name='Sana')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currency.currency', verbose_name='Valyuta')),
            ],
            options={
                'verbose_name': 'Valyuta kursi',
                'verbose_name_plural': 'Valyuta kurslari',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['currency', '-date'], name='currency_cu_currenc_4e092a_idx')],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
