# Generated by Django 5.2.16 on 2026-07-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Bosh sahifadagi medalyon va grafikda ko‘rsatiladi. Ko‘p valyuta belgilansa grafik o‘qilmay qoladi — 3-4 tadan oshirmang.', verbose_name='Bosh sahifada'),
        ),
    ]
