# Generated by Django 5.2.16 on 2026-07-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currency_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='image',
            field=models.ImageField(blank=True, help_text='Valyuta uchun rasm (masalan, oltin tanga).', null=True, upload_to='currency/', verbose_name='Rasm'),
        ),
    ]
