# Generated by Django 5.2.16 on 2026-07-14 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug (URL)')),
                ('latitude', models.FloatField(verbose_name='Kenglik (lat)')),
                ('longitude', models.FloatField(verbose_name='Uzunlik (lon)')),
                ('is_default', models.BooleanField(default=False, help_text='Ticker va bosh sahifada ko‘rsatiladi (odatda Toshkent)', verbose_name='Asosiy shahar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Shahar',
                'verbose_name_plural': 'Shaharlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('temp_now', models.SmallIntegerField(blank=True, null=True, verbose_name='Hozirgi harorat (°C)')),
                ('temp_min', models.SmallIntegerField(verbose_name='Eng past (°C)')),
                ('temp_max', models.SmallIntegerField(verbose_name='Eng baland (°C)')),
                ('condition', models.CharField(choices=[('clear', 'Ochiq ☀️'), ('partly', 'Bulutli ochiq ⛅'), ('cloudy', 'Bulutli ☁️'), ('fog', 'Tuman 🌫'), ('rain', 'Yomg‘ir 🌧'), ('snow', 'Qor ❄️'), ('thunder', 'Momaqaldiroq ⛈')], default='clear', max_length=12, verbose_name='Holat')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='weather.city', verbose_name='Shahar')),
            ],
            options={
                'verbose_name': 'Ob-havo prognozi',
                'verbose_name_plural': 'Ob-havo prognozlari',
                'ordering': ['city', 'date'],
                'indexes': [models.Index(fields=['city', 'date'], name='weather_wea_city_id_1dca0e_idx')],
                'unique_together': {('city', 'date')},
            },
        ),
    ]
