# Generated by Django 5.2.16 on 2026-07-17 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('hour', models.PositiveSmallIntegerField(verbose_name='Soat (0–23)')),
                ('temp', models.SmallIntegerField(verbose_name='Harorat (°C)')),
                ('feels', models.SmallIntegerField(blank=True, null=True, verbose_name='His qilinishi (°C)')),
                ('condition', models.CharField(choices=[('clear', 'Ochiq ☀️'), ('partly', 'Bulutli ochiq ⛅'), ('cloudy', 'Bulutli ☁️'), ('fog', 'Tuman 🌫'), ('rain', 'Yomg‘ir 🌧'), ('snow', 'Qor ❄️'), ('thunder', 'Momaqaldiroq ⛈')], default='clear', max_length=12, verbose_name='Holat')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly', to='weather.city', verbose_name='Shahar')),
            ],
            options={
                'verbose_name': 'Soatlik ob-havo',
                'verbose_name_plural': 'Soatlik ob-havo',
                'ordering': ['city', 'date', 'hour'],
                'indexes': [models.Index(fields=['city', 'date', 'hour'], name='weather_hou_city_id_2f9166_idx')],
                'unique_together': {('city', 'date', 'hour')},
            },
        ),
    ]
